### ISSUE TITLE
CRITICAL: Invalid method Mageplaza\SocialLogin\Block\Form\Register::isGdprProEnabled

### ISSUE THREAD

**Issue by AboElnoor** [mageplaza/magento-2-social-login#146] opened 2019-08-07 12:19 UTC
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.1.30
3. MySQL: 5.7.26

### Steps to reproduce

1. Install the extension.
2. Enable it from the admin panel.
3. I didn't add my social apps credentials.
4. I didn't change the default settings.

### Exception received

I get a fatal error every time I open my home page.
[This is the full exception from sentry platform](http://sentry.nobaj.com/share/issue/b7b71a9fd9f74565adb6f64b5a7a1def/)

**Comment by Desmond-Mageplaza** [comment] 2019-08-07 15:04
Hi @AboElnoor 

I think you are using an old version of the Social Login module.
This error is caused by an incomplete code clean-up from our side so I'm really sorry for this.
Could you update the module to your latest version?
Then let me know the result.

**Comment by AboElnoor** [comment] 2019-08-07 15:57
Hi @Desmond-Mageplaza 
I've run composer update on my project and the issue still appears.
This is my version from composer.json file `"mageplaza/magento-2-social-login": "^2.7",`

**Comment by Desmond-Mageplaza** [comment] 2019-08-08 01:48
Hi @AboElnoor 
Please select and submit a new ticket from this URL
https://www.mageplaza.com/contact.html
I will perform a quick check-up for the Social Login module
Thank you.

**Comment by Desmond-Mageplaza** [comment] 2019-08-14 07:30
Hi @AboElnoor
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.

**Closed by Desmond-Mageplaza** 2019-08-14 07:30 UTC
